name: Workflow CI
description: A workflow that calls reusable and composite workflows
permissions:
  contents: read
on: [push, pull_request]
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow-for-ci.yml

  call-composite-workflow:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Greeting Workflow
        uses: ./.github/actions/composite-workflow
        with:
          name: "Environment: ${{ vars.ENVIRONMENT_NAME }}"
          message: "Hola"
